CREATE TABLE DEPT
(
Deptno NUMBER(2)PRIMARY KEY.
Deptname VARCHAR( 10) ,
Manager VARCHAR( 10),
PhoneNumber Char( 12)
):
CREATE TABLE EMP
( Empno NUMBER(4)PRIMARY KEY
Ename VARCHAR( 10),
Age NUMBER(2),
Job VARCHAR(9),
Sal NUMBER(7,2)
Deptno NUMBER(2),
CONSTRAINT C1 CHECK( Age< = 60).CONSTRAINT FK_DEPTNO FOREIGN KEY( Depto)REFERENCES DEPT( Deptno)
) ;